'use client'

import { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import {
  ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight,
  Plus, Pencil, Trash2, X, Save, Wand2, ChevronsRight as SelectArrow, Loader2, Search
} from "lucide-react";
import { createRecord, updateRecord, deleteRecord, generateSmartId } from "../../actions";

interface TableClientProps {
  table: string;
  data: any[];
  columns: string[];
  schema: any[];
  references: Record<string, any[]>;
  total: number;
  page: number;
  limit: number;
  initialSearch: string;
}

export default function TableClient({
  table, data, columns, schema, references, total, page, limit, initialSearch
}: TableClientProps) {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const totalPages = Math.ceil(total / limit);
  const primaryKey = schema.find((col: any) => col.pk === 1)?.name || columns[0];

  const [searchTerm, setSearchTerm] = useState(initialSearch);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<any>(null);
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [isLoading, setIsLoading] = useState(false);
  const [isGeneratingId, setIsGeneratingId] = useState(false);

  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      if (searchTerm !== initialSearch) {
        const params = new URLSearchParams(searchParams);
        if (searchTerm) {
          params.set('query', searchTerm);
        } else {
          params.delete('query');
        }
        params.set('page', '1');
        router.replace(`${pathname}?${params.toString()}`);
      }
    }, 500);

    return () => clearTimeout(delayDebounceFn);
  }, [searchTerm, router, pathname, searchParams, initialSearch]);

  const handleAddNew = () => {
    setEditingItem(null);
    setFormData({});
    setIsModalOpen(true);
  };

  const handleEdit = (item: any) => {
    setEditingItem(item);
    setFormData({ ...item });
    setIsModalOpen(true);
  };

  const handleGenerateId = async (colName: string) => {
    setIsGeneratingId(true);
    try {
      const newId = await generateSmartId(table, colName);
      setFormData(prev => ({ ...prev, [colName]: newId }));
    } catch (error) {
      alert("Failed: " + error);
    } finally {
      setIsGeneratingId(false);
    }
  };

  const handleDelete = async (id: string | number) => {
    if (!confirm("Are you sure?")) return;
    try {
      await deleteRecord(table, id);
      router.refresh();
    } catch (e) {
      alert("Failed: " + e);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      if (editingItem) {
        await updateRecord(table, editingItem[primaryKey], formData);
      } else {
        await createRecord(table, formData);
      }
      setIsModalOpen(false);
      router.refresh();
    } catch (err) {
      alert("Error: " + err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleInputChange = (col: string, value: string) => {
    setFormData(prev => ({ ...prev, [col]: value }));
  };

  const isAutoGenerated = (colName: string) => {
    const autoFields = ['signup_date', 'order_date', 'review_date', 'event_timestamp', 'created_at'];
    return autoFields.includes(colName);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold capitalize text-gray-900">{table}</h1>
          <p className="text-gray-500 mt-1">Raw Data • {total.toLocaleString()} records</p>
        </div>

        <div className="flex items-center gap-3">

          <div className="relative group">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-blue-500 transition-colors" />
            <input
              type="text"
              placeholder="Filter..."
              className="pl-9 pr-4 py-2 bg-white border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all w-40 focus:w-60"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          <div className="h-6 w-px bg-gray-200 mx-1 hidden md:block"></div>

          <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-gray-200 shadow-sm">
            <span className="text-xs text-gray-500 font-medium uppercase">Show</span>
            {[50, 100, 1000].map(size => (
              <Link
                key={size}
                href={`${pathname}?query=${searchTerm}&page=1&limit=${size}`}
                className={`px-2 py-1 text-xs font-bold rounded transition-colors ${limit === size ? 'bg-black text-white' : 'text-gray-500 hover:bg-gray-100'
                  }`}
              >
                {size}
              </Link>
            ))}
          </div>

          <button onClick={handleAddNew} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium shadow-sm transition-all">
            <Plus className="w-4 h-4" /> Add
          </button>
        </div>
      </div>

      {/* Data Table */}
      <div className="bg-white rounded-3xl shadow-[0_4px_20px_rgba(0,0,0,0.02)] border border-gray-100/50 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-gray-50/80 text-gray-500 border-b border-gray-100 backdrop-blur-sm sticky top-0">
              <tr>
                {columns.map(col => (
                  <th key={col} className="p-4 font-semibold uppercase text-[11px] tracking-wider whitespace-nowrap">
                    {col.replace('_', ' ')}
                  </th>
                ))}
                <th className="p-4 w-20 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {data.length > 0 ? data.map((row: any, i: number) => (
                <tr key={i} className="group hover:bg-blue-50/30 transition-colors">
                  {columns.map(col => (
                    <td key={col} className="p-4 whitespace-nowrap text-gray-700 font-medium group-hover:text-gray-900">
                      {typeof row[col] === 'string' && row[col].length > 40 ? row[col].substring(0, 40) + '...' : row[col]}
                    </td>
                  ))}
                  <td className="p-4 text-right">
                    <div className="flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button onClick={() => handleEdit(row)} className="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors">
                        <Pencil className="w-4 h-4" />
                      </button>
                      <button onClick={() => handleDelete(row[primaryKey])} className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              )) : (
                <tr>
                  <td colSpan={columns.length + 1} className="p-8 text-center text-gray-500">
                    No records found matching "{searchTerm}"
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="p-4 border-t border-gray-100 bg-gray-50/50 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="text-sm text-gray-500">
            Page <span className="font-medium">{page}</span> of <span className="font-medium">{totalPages || 1}</span>
          </div>
          <div className="flex items-center gap-2">
            <PaginationLink href={`${pathname}?query=${searchTerm}&page=${page - 1}&limit=${limit}`} disabled={page <= 1} icon={<ChevronLeft className="w-4 h-4" />} />
            <PaginationLink href={`${pathname}?query=${searchTerm}&page=${page + 1}&limit=${limit}`} disabled={page >= totalPages} icon={<ChevronRight className="w-4 h-4" />} />
          </div>
        </div>
      </div>

      {/* Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/20 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh]">
            <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
              <h3 className="font-bold text-lg text-gray-900">
                {editingItem ? `Edit ${table}` : `New ${table}`}
              </h3>
              <button onClick={() => setIsModalOpen(false)}><X className="w-5 h-5 text-gray-400" /></button>
            </div>

            <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6 space-y-5">
              {schema.map((col: any) => {
                const isFK = references[col.name];
                const isPK = col.pk === 1;
                const isAuto = isAutoGenerated(col.name);

                if (isAuto) return null;

                return (
                  <div key={col.name}>
                    <div className="flex justify-between items-center mb-1">
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">
                        {col.name.replace(/_/g, ' ')} {isPK && <span className="text-blue-500">(PK)</span>}
                      </label>

                      {isPK && !editingItem && (
                        <button
                          type="button"
                          onClick={() => handleGenerateId(col.name)}
                          disabled={isGeneratingId}
                          className="text-xs text-blue-600 hover:text-blue-700 flex items-center gap-1 font-medium disabled:opacity-50"
                        >
                          {isGeneratingId ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand2 className="w-3 h-3" />}
                          Auto Generate
                        </button>
                      )}
                    </div>

                    {isFK ? (
                      <div className="relative">
                        <select
                          className="w-full px-3 py-2.5 bg-gray-50 border border-transparent rounded-lg text-sm focus:bg-white focus:border-blue-500/20 focus:ring-4 focus:ring-blue-500/10 outline-none transition-all appearance-none cursor-pointer font-medium"
                          value={formData[col.name] || ''}
                          onChange={(e) => handleInputChange(col.name, e.target.value)}
                        >
                          <option value="">Select Reference...</option>
                          {isFK.map((opt: any) => (
                            <option key={opt.value} value={opt.value}>
                              {opt.label} ({String(opt.value).substring(0, 5)}...)
                            </option>
                          ))}
                        </select>
                        <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400">
                          <SelectArrow className="w-4 h-4 rotate-90" />
                        </div>
                      </div>
                    ) : (
                      <input
                        type={col.type === 'INTEGER' || col.type === 'REAL' ? 'number' : 'text'}
                        className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all font-medium placeholder:font-normal"
                        placeholder={`Enter ${col.name}...`}
                        value={formData[col.name] || ''}
                        onChange={(e) => handleInputChange(col.name, e.target.value)}
                        readOnly={isPK && editingItem}
                        disabled={isPK && editingItem}
                      />
                    )}
                  </div>
                );
              })}
            </form>

            <div className="p-6 border-t border-gray-100 bg-gray-50/50 flex justify-end gap-3">
              <button onClick={() => setIsModalOpen(false)} className="px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-200/50 rounded-lg">Cancel</button>
              <button onClick={handleSubmit} disabled={isLoading} className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg shadow-sm disabled:opacity-50">
                {isLoading ? 'Saving...' : 'Save Record'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function PaginationLink({ href, disabled, icon }: any) {
  if (disabled) return <button disabled className="p-2 rounded-lg text-gray-300 cursor-not-allowed">{icon}</button>;
  return <Link href={href} className="p-2 rounded-lg text-gray-500 hover:bg-white hover:text-gray-900 hover:shadow-sm border border-transparent hover:border-gray-200 transition-all">{icon}</Link>;
}
